Investing/Controllers/BondController.cs
using Investing.Services.MoexData;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Investing.Controllers
{
    public class BondController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> GetListBonds()
        {
            BondData bondData = new BondData();
            return View(await bondData.CombinedBondDataAsync());
        }
    }
}

Investing/Controllers/FundController.cs
using Investing.Services.MoexData;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Investing.Controllers
{
    public class FundController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> GetListFunds()
        {
            FundData fundData = new FundData();
            return View(await fundData.CombinedFundDataAsync());
        }
    }
}

Investing/Views/Shared/_Layout.cshtml
@using Investing.Extensions;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Investing</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/layout.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<script src="https://kit.fontawesome.com/fce9a50d02.js"
        crossorigin="anonymous">
    </script>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <div class="section-main-window">
                    <div class="logo-proaile">
                        <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/images/logo.jpg" alt="Профиль" class="logo-btn"></a>
                      </div>
                    <div class="section-account navbar-collapse collapse d-sm-inline-flex">
                        <ul class="navbar-nav flex-grow-1">
                            @if (!Context.Session.IsAuthenticated())
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="LoginAccount"><i class="fa-solid fa-door-open"></i>Войти</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="OpenInvestingAccount"><i class="fa-solid fa-star"></i>Открыть счет</a>
                                </li>
                            }
                            else
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-door-open"></i>Выйти</a>
                                </li>
                            }
                            </ul>
                        </div>
                </div>
               </div> 
        </nav> 
        <div class="container">
        <nav class="top-menu">
            <ul class="menu-main">
                    <li><a asp-controller="Stock" asp-action="GetListStocks" id="instrumentBtn()" class="instrument-btn">Акции</a></li>
                    <li><a asp-controller="Currency" asp-action="GetListCurrency" id="instrumentBtn()" class="instrument-btn">Валюта</a></li>
                    <li><a asp-controller="Bond" asp-action="GetListBonds" id="instrumentBtn()" class="instrument-btn">Облигации</a></li>
                    <li><a asp-controller="Fund" asp-action="GetListFunds" id="instrumentBtn()" class="instrument-btn">Фонды</a></li>
                    <li><a asp-controller="Futures" asp-action="GetListFutures" id="instrumentBtn()" class="instrument-btn">Фьючерсы</a></li>
            </ul>
        </nav>
        </div>
        <div class="container">
            <div class="search-container">
                <form asp-controller="Instrument" asp-action="GetListInstruments" id="text-srch" method="get"> 
                    <input name="substring" class="input-srch" id="searchInput" type="text"
                           placeholder="Поиск по названию, тикерy или ISIN-коду"
                           oninput="debouncedSearch()"
                           onfocus="handleFocus()"
                           autocomplete="off">
                    <button class="srch-button" type="submit" onclick="searchOnServer()">
                        <i class="fa-solid fa-magnifying-glass"></i>
                    </button>
                    <div class="dropdown-results" id="dropdownResults">
                        <ul id="dropdown-src"></ul>
                    </div>
                </form>
            </div>
        </div>
     </header>
     <script>
        document.addEventListener('DOMContentLoaded', function () {
            loadAllInstruments();
        });
     </script>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Investing - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/layout.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>