Investing/Models/Currency.cs
using Investing.Models;
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Investing.Models
{
    public class Currency
    {
        public CurrencySecurity Security { get; set; }
        public CurrencyMarketdata Marketdata { get; set; }
    }

    public class CurrencySecurity : UnionModelInstrumentSecurity
    {
        public int LOTSIZE { get; set; }
        public string SETTLEDATE { get; set; }
        public int FACEVALUE { get; set; }
        public string MARKETCODE { get; set; }
        public string PREVDATE { get; set; }
        public object REMARKS { get; set; }
        public string STATUS { get; set; }
        public string FACEUNIT { get; set; }
        public decimal? PREVWAPRICE { get; set; }
        public string CURRENCYID { get; set; }
        public int LOTDIVIDER { get; set; }
    }

    public class CurrencyMarketdata : UnionModelInstrumentMarketdata
    {
        public object HIGHBID { get; set; }
        public decimal LASTCNGTOLASTWAPRICE { get; set; }
        public decimal? WAPRICE { get; set; }
        public float WAPTOPREVWAPRICE { get; set; }
        public float? CLOSEPRICE { get; set; }
        public string TRADINGSTATUS { get; set; }
        public float WAPTOPREVWAPRICEPRCNT { get; set; }
        public float? CHANGE { get; set; }
        public float VALUE { get; set; }
        public float? VALUE_USD { get; set; }
        public int QTY { get; set; }
        public decimal? PRICEMINUSPREVWAPRICE { get; set; }
        public long? VALTODAY_RUR { get; set; }
        public decimal? MARKETPRICE { get; set; }
        public decimal? MARKETPRICETODAY { get; set; }
        public decimal? MARKETPRICE2 { get; set; }
        public object ADMITTEDQUOTE { get; set; }
        public decimal? LOPENPRICE { get; set; }
    }
}

Investing/Controllers/CurrencyController.cs
using Investing.Services.MoexData;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Investing.Controllers
{
    public class CurrencyController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> GetListCurrency()
        {
            CurrencyData  currencyData = new CurrencyData();
            return View(await currencyData.CombinedCurrencyDataAsync());
        }
    }
}

Investing/Views/Currency/GetListCurrency.cshtml
@model List<Investing.Models.Currency>

<script src="~/js/currency.js"></script>
<link rel="stylesheet" href="~/css/currency.css" />
@{
    ViewData["Title"] = "Валюта Московской биржи";
}

<h1>Валюта Московской биржи</h1>

<div>
    <div class="selector-currrency">
        <div class="visible-selectr-currency">
            <h4 id="visible-currency-name"></h4>
        </div>
    <div class="section-type-currency">
        <div class="section-btns-type">
            <button onclick="getAllCurrency()" id="btn-type-currrency-all" class="btn-type-currrency">Все</button>
            <button onclick="getNededCurrency()" id="btn-type-currrency-money()" class="btn-type-currrency">Денежные средства</button>
            <button onclick="getNededMetalls()" id="btn-type-currrency-metall()" class="btn-type-currrency">Драгоценные металлы</button>
            </div>
        </div>
    </div>
<table class="table" id="table-currency">
    <thead>
        <tr>
            <th onclick="sortTable(0)">
                Название
            </th>
            <th onclick="sortTable(1)">
                Цена
            </th>
            <th onclick="sortTable(2)">
                За день
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var currency in Model)
        {
            @if (currency.Marketdata.LAST.HasValue)
            {
             <tr style="@(currency.Marketdata?.TRADINGSTATUS == "N" ? "background-color: grey" : "background-color: white;")" onclick="window.location.href='@Url.Action("DetailCurrency", "Currency", new { secId = currency.Security.SECID })'; return false">
                <td>
                    <div class="company-info">
                        @if (!(currency.Security.IconCompany is null))
                        {
                            <img src="@String.Format("data:image/gif;base64,{0}", Convert.ToBase64String(@currency.Security.IconCompany))" class="company-logo">
                        }
                        else
                        {
                            <img src="~/images/logo.jpg" class="company-logo" />
                        }
                        <div>
                            <div class="company-name">@currency.Security.SHORTNAME</div>
                            <p class="company-description">От @currency.Security.LOTSIZE @currency.Security.FACEUNIT</p>
                        </div>
                    </div>
                </td>
                <td>@currency.Marketdata.LAST</td>

                        @{
                            string isWherePrice = "";
                            if(currency.Marketdata.LASTTOPREVPRICE > 0.1M)
                            {
                                isWherePrice = "plus-result";
                            }
                            else
                            {
                                isWherePrice = "minus-result";
                            }
                        }

            <td class="@isWherePrice">@currency.Marketdata.LASTTOPREVPRICE </td>
            </tr>   
            }
        }
    </tbody>
    </table>
</div>