Investing/Models/Stock.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace Investing.Models
{
    [Table("stock")]
    public class Stock
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }

        [Required]
        [Column("name")]
        [DisplayName("Наименование акции")]
        public string Name { get; set; }

        [Required]
        [Column("short_description")]
        [DisplayName("Краткое описание акции")]
        public string ShortDesc { get; set; }

        [DisplayName("Описание акции")]
        [Column("description")]
        public string Description { get; set; }

        [DisplayName("Стоимость акции")]
        [Column("price")]
        [Range(1, int.MaxValue)]
        [Required]
        public double Price { get; set; }

        [DisplayName("Количество акций в лоте")]
        [Range(1, int.MaxValue)]
        [Column("lot_quantity")]
        [Required]
        public int LotQuantity { get; set; }

        [Column("category_id")]
        [Range(1, long.MaxValue)]
        [Required]
        public long CategoryId { get; set; }

        #region Устанавливаем связь между Продуктом и Категорией

        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }
        #endregion

    }
}

Investing/Models/Stocks.cs
using System;

namespace Investing.Models
{
    public class Stocks
    {
        public SecurityStock Security { get; set; }
        public MarketdataStock Marketdata { get; set; }
    }

    //единая модель под все типы инструментов
    public class UnionModelInstruments
    {
        public UnionModelInstrumentSecurity Securities { get; set; }
        public UnionModelInstrumentMarketdata Marketdata { get; set; }
    }

    public interface IExpressionNumberMoex
    {
        string SECID { get; set; }
    }
    public class UnionModelInstrumentSecurity : IExpressionNumberMoex
    {
        public string? BOARDID { get; set; }
        public string? SHORTNAME { get; set; }
        public string? SECNAME { get; set; }
        public int? DECIMALS { get; set; }
        public float? MINSTEP { get; set; }
        public string? LATNAME { get; set; }
        public float? PREVPRICE { get; set; }
        public string? SECID { get; set;}
        public byte[]? IconCompany { get; set; }
    }
    public class UnionModelInstrumentMarketdata : IExpressionNumberMoex
    {
        public string? SECID { get; set; }
        public string? BOARDID { get; set; }
        public float? BID { get; set; }
        public int? BIDDEPTH { get; set; }
        public float? OFFER { get; set; }

        public int? OFFERDEPTH { get; set; }
        public long? OFFERDEPTHT { get; set; }
        public float? SPREAD { get; set; }
        public long? BIDDEPTHT { get; set; }
        public float? OPEN { get; set; }
        public float? LOW { get; set; }
        public float? HIGH { get; set; }
        public decimal? LAST { get; set; }
        public int? LASTCHANGE { get; set; }
        public decimal? LASTCHANGEPRCNT { get; set; }
        public decimal? LASTTOPREVPRICE { get; set; }
        public long? NUMTRADES { get; set; }
        public long? VOLTODAY { get; set; }
        public long? VALTODAY { get; set; }
        public int? VALTODAY_USD { get; set; }
        public string? UPDATETIME { get; set; }
        public int? NUMBIDS { get; set; }
        public int? NUMOFFERS { get; set; }
        public string? TIME { get; set; }
        public long? SEQNUM { get; set; }
        public string? SYSTIME { get; set; }
    }


    public class SecurityStock : UnionModelInstrumentSecurity
    {
        public int LOTSIZE { get; set; }
        public float FACEVALUE { get; set; }
        public string STATUS { get; set; }
        public string BOARDNAME { get; set; }
        public object REMARKS { get; set; }
        public string MARKETCODE { get; set; }
        public string INSTRID { get; set; }
        public object SECTORID { get; set; }
        public float? PREVWAPRICE { get; set; }
        public string FACEUNIT { get; set; }
        public string PREVDATE { get; set; }
        public double ISSUESIZE { get; set; }
        public string ISIN { get; set; }
        public string REGNUMBER { get; set; }
        public float? PREVLEGALCLOSEPRICE { get; set; }
        public string CURRENCYID { get; set; }
        public string SECTYPE { get; set; }
        public int LISTLEVEL { get; set; }
        public string SETTLEDATE { get; set; }

    }

    public class MarketdataStock : UnionModelInstrumentMarketdata
    {
        public string? SECID { get; set; }
        public decimal? QTY { get; set; }
        public decimal? VALUE { get; set; }
        public float? VALUE_USD { get; set; }
        public float? WAPRICE { get; set; }
        public decimal? LASTCNGTOLASTWAPRICE { get; set; }
        public float? WAPTOPREVWAPRICEPRCNT { get; set; }
        public float? WAPTOPREVWAPRICE { get; set; }
        public decimal? CLOSEPRICE { get; set; }
        public float? MARKETPRICETODAY { get; set; }
        public decimal? MARKETPRICE { get; set; }
        public float? ETFSETTLEPRICE { get; set; }
        public string? TRADINGSTATUS { get; set; }
        public float? LASTBID { get; set; }
        public float? LASTOFFER { get; set; }
        public float? LCLOSEPRICE { get; set; }
        public float? LCURRENTPRICE { get; set; }
        public decimal? MARKETPRICE2 { get; set; }
        public decimal? CHANGE { get; set; }
        public float? HIGHBID { get; set; }
        public float? LOWOFFER { get; set; }
        public float? PRICEMINUSPREVWAPRICE { get; set; }
        public float? OPENPERIODPRICE { get; set; }
        public float? CLOSINGAUCTIONPRICE { get; set; }
        public int? CLOSINGAUCTIONVOLUME { get; set; }
        public decimal? ISSUECAPITALIZATION { get; set; }
        public string? ISSUECAPITALIZATION_UPDATETIME { get; set; }
        public object? ETFSETTLECURRENCY { get; set; }
        public long? VALTODAY_RUR { get; set; }
        public string? TRADINGSESSION { get; set; }
        public float? TRENDISSUECAPITALIZATION { get; set; }
    }
}

Investing/Controllers/StockController.cs
using DevTrends.MvcDonutCaching;
using Investing.Data;
using Investing.Models;
using Investing.Models.ViewModels;
using Investing.Services;
using Investing.Services.Interfaces;
using Investing.Services.MoexData;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;



namespace Investing.Controllers
{
    public class StockController : Controller
    {
        private readonly MainContext _context;
        IDetailInstrument<Stocks> _detailInstrument;
        public StockController(MainContext context, IDetailInstrument<Stocks> detailInstrument)
        {
            _context = context;
            _detailInstrument = detailInstrument;
        }

        [HttpGet]
        public async Task<IActionResult> GetListStocks()
        {
            StockData stockData = new StockData();
            return View(await stockData.CombinedStockDataAsync());
        }

        public async Task<ActionResult> DetailStock(string secId)
        {
            var stock = await _detailInstrument.DetailInstrument(secId, FullModelInstrumentsMoex.TypeInstrument.Stock);
            return View(stock);
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<Stock>> GetStockById(long id)
        {
            var stock = await _context.Stock.FindAsync(id);

            if (stock == null)
            {
                return NotFound();
            }

            return stock;
        }

        public async Task<ActionResult<Stock>> ProcessingFinancialInstrument(long secid) //ISIN(Международный идентификационный номер ценной бумаги)
        {
            var stock = await _context.Stock.FindAsync(secid);

            if (stock == null)
            {
                return NotFound();
            }

            return stock;
        }
    }
}

Investing/Views/Stock/DetailStock.cshtml
@model Investing.Models.Stocks
<link rel="stylesheet" href="~/css/detail_stock.css" />
<script src="~/js/detail_stock.js"></script>
<script src="~/js/candles_history.js"></script>
<div class="main_board">
    <div class="main-section">
        <div class="section not-space">
         <div class="logo-name-main">
                    @if (!(Model.Security.IconCompany is null))
                    {
                        <img src="@String.Format("data:image/gif;base64,{0}", Convert.ToBase64String(Model.Security.IconCompany))" class="company-logo">
                    }
                    else
                    {
                        <img src="~/images/logo.jpg" class="company-logo" />
                    }
                <div class="name-company">
                    <h2>@Model.Security.SHORTNAME</h2>
                </div>
      </div>
            <div class="btn-instrument">
                <div class="btn-buy-instrument">
                    <button class="btn-buy">Купить</button>
                </div>
                <div class="btn-sell-instrument">
                    <button class="btn-sell">Продать</button>
                </div>
            </div>
     </div>
    <div class="section">
        <div class="price-now">
            <div class="info-price">
                <p>Цена</p>
                <h4> @Model.Marketdata.OFFER</h4>
            </div>
         </div>
            <div class="change-price">
                <div class="select-price">
                    <p>Изменение за день</p>
                    <div class="change-price-num-persent">
                        <h6 class="change-price-num" id="change-price-num"></h6>
                        <h6 id="change-price-persent"></h6>
                    </div>
                </div>
            </div>
         <div class="type-instrument">
                <p>Акция</p>
         </div>
            <div class="lot-size">
                <p>Лот = @Model.Security.LOTSIZE шт.</p>
            </div>
         <div class="sec-id-company">
                <p id="secid-name-p">@Model.Security.SECID</p>
         </div>
    </div>
        <div class="tab">
            <button class="tablinks" onclick="openTab(event, 'Tab1')">Обзор</button>
            <button class="tablinks" onclick="openTab(event, 'Tab2')">История</button>
        </div>
        <div id="Tab1" class="tabcontent">
            <div class="section">
            <div class="diagram-instruments">
                <div class="diagram-chart-section" >
                            <div class="preloader" id="chart-preloader">
                                <div class="spinner">
                                    <i class="fa-solid fa-spinner"></i>
                                </div>
                                <p>Загрузка данных...</p>
                            </div>
                        <canvas id="chart-instruments"></canvas>
                    </div>
                        <div class="date-diagram">
                        <div class="section-btn-date-diagram">
                                <button onclick="getGlassOrdersToday()" id="btn_diagram_1d" class="btn-date-diagram" href="#">1 д</button>
                                <button onclick="getGlassOrders(event)" id="btn_diagram_1w" class="btn-date-diagram" href="#">1 н</button>
                                <button onclick="getGlassOrders(event)" id="btn_diagram_1m" class="btn-date-diagram" href="#">1 м</button>
                                <button onclick="getGlassOrders(event)" id="btn_diagram_3m" class="btn-date-diagram" href="#">3 м</button>
                                <button onclick="getGlassOrders(event)" id="btn_diagram_6m" class="btn-date-diagram" href="#">6 м</button>
                                <button onclick="getGlassOrders(event)" id="btn_diagram_1y" class="btn-date-diagram" href="#">1 г</button>
                           </div> 
                        </div>
                </div>
            </div>
            <div class="section">
                <div class="glass-trading">
                    <div class="up-section-glass-trading">
                        <h5>Стакан</h5>
                         <button class="btn-detail-glass">Показать подробно</button>
                    </div>
                    <div class="down-section-glass-trading">
                             <div class="demand-section">
                                  Спрос, Р
                                 <progress class="progress-demand" id="progress-demand" max="100" value="70">70%</progress>
                              </div>
                                   <div class="offer-section">
                                    Предлжение, Р
                            <progress class="progress-offer" id="progress-offer" max="100" value="70">70%</progress>
                                </div>
                    </div>
                    @* стакан со спросом и предложением *@
                </div>
            </div>
            <div class="section">
            <div class="statistics-today-section">
                <div class="statistics-today-name">
                    <h2>Ключевая статистика за сегодня</h2>
                </div>
                <div class="statistics-today-details">
                    <div class="left-statistics-today">
                        <p>Цена закрытия:  @Model.Security.PREVLEGALCLOSEPRICE</p>
                        <p>Цена закрытия:  @Model.Marketdata.OPEN</p>
                        <p>Количество акций в обращении:  @Model.Security.ISSUESIZE</p>
                    </div>
                    <div class="right-statistics-today">
                        <p>Минимальная цена:  @Model.Marketdata.LOW</p>
                        <p>Максимальная цена:  @Model.Marketdata.HIGH</p>
                        <p>Количество сделок за сегодня:  @Model.Marketdata.NUMTRADES</p>
                    </div>
                </div>
                </div>
            </div>
        </div>
        <div id="Tab2" class="tabcontent">
            <div class="section not-space">
                <div class="transactions asdf">
                    <select class="combobox-histories-trading" name="city" id="city-select">
                        <option value="">Сделки</option>
                        <option value="petersburg">Санкт-Петербург</option>
                        <option value="samara">Самара</option>
                        <option value="perm">Пермь</option>
                        <option value="novosibirsk">Новосибирск</option>
                    </select>
                </div>
                <div class="scores asdf">
                    <select class="combobox-histories-trading" name="city" id="city-select">
                        <option value="">Счета</option>
                        <option value="petersburg">Санкт-Петербург</option>
                        <option value="samara">Самара</option>
                        <option value="perm">Пермь</option>
                        <option value="novosibirsk">Новосибирск</option>
                    </select>
                </div>
                <div class="period asdf">
                    <select class="combobox-histories-trading" name="city" id="city-select">
                        <option value="">Период</option>
                        <option value="petersburg">Санкт-Петербург</option>
                        <option value="samara">Самара</option>
                        <option value="perm">Пермь</option>
                        <option value="novosibirsk">Новосибирск</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var allInstruments = @Html.Raw(Json.Serialize(Model));
    document.getElementsByClassName("tablinks")[0].click();
</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

Investing/Views/Stock/GetListBonds.cshtml
@model List<Investing.Models.ViewModels.BondItemVM>

@{
    ViewData["Title"] = "Облигации Московской биржи";
}

<h1>Облигации Московской биржи</h1>

<table class="table" id="sortTable">
    <thead>
        <tr>
            <th>Тикер</th>
            <th>Название</th>
            <th>Цена</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Security.SECID</td>
                <td>@item.Security.SHORTNAME</td>
                <td>@(item.Marketdata?.MARKETPRICE2?.ToString() ?? item.Marketdata?.LAST?.ToString() ?? item.Security?.PREVPRICE?.ToString() ?? "-")</td>
            </tr>
        }
    </tbody>
</table>

Investing/Views/Stock/GetListCurrency.cshtml
@model List<Investing.Models.ViewModels.CombinedCurrencyVM>

@{
    ViewData["Title"] = "Валюты Московской биржи";
}

<h1>Валюты Московской биржи</h1>

<table class="table" id="sortTable">
    <thead>
        <tr>
            <th>Название</th>
            <th>Цена</th>
            <th>За день</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Security.ShortName</td>
                <td>@item.Marketdata.Last</td>
                @* <td>@(item.Marketdata?.MARKETPRICE2?.ToString() ?? item.Marketdata?.LAST?.ToString() ?? item.Security?.PREVPRICE?.ToString() ?? "-")</td> *@
            </tr>
        }
    </tbody>
</table>

Investing/Views/Stock/GetListFunds.cshtml
@model List<Investing.Models.ViewModels.FundItemVM>

@{
    ViewData["Title"] = "Фонды (ETF) Московской биржи";
}

<h1>Фонды (ETF) Московской биржи</h1>

<table class="table" id="sortTable">
    <thead>
        <tr>
            <th>Тикер</th>
            <th>Название</th>
            <th>Цена</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Security.SECID</td>
                <td>@item.Security.SHORTNAME</td>
                <td>@(item.Marketdata?.MARKETPRICE2?.ToString() ?? item.Marketdata?.LAST?.ToString() ?? item.Security?.PREVPRICE?.ToString() ?? "-")</td>
            </tr>
        }
    </tbody>
</table>

Investing/Views/Stock/GetListFutures.cshtml
@model List<Investing.Models.ViewModels.FutureItemVM>

@{
    ViewData["Title"] = "Фьючерсы Московской биржи";
}

<h1>Фьючерсы Московской биржи</h1>

<table class="table" id="sortTable">
    <thead>
        <tr>
            <th>Тикер</th>
            <th>Название</th>
            <th>Цена</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Security.SECID</td>
                <td>@item.Security.SHORTNAME</td>
                <td>@(item.Marketdata?.LAST?.ToString() ?? "-")</td>
            </tr>
        }
    </tbody>
</table>

Investing/Views/Stock/GetListStocks.cshtml
@model List<Investing.Models.Stocks> 

@{
    ViewData["Title"] = "Акции Московской биржи";
}

<h1>Акции Московской биржи</h1>

<table class="table" id="sortTable">
    <thead>
        <tr>
            <th onclick="sortTable(0)">
                Тикер
                <span class="sort-icon">
                    <svg class="asc" viewBox="0 0 24 24" width="12" height="12">
                        <path d="M7 14l5-5 5 5z"></path>
                    </svg>
                    <svg class="desc" viewBox="0 0 24 24" width="12" height="12">
                        <path d="M7 10l5 5 5-5z"></path>
                    </svg>
                </span>
            </th>
            <th onclick="sortTable(1)">
                Название
                <span class="sort-icon">
                    <svg class="asc" viewBox="0 0 24 24" width="12" height="12">
                        <path d="M7 14l5-5 5 5z"></path>
                    </svg>
                    <svg class="desc" viewBox="0 0 24 24" width="12" height="12">
                        <path d="M7 10l5 5 5-5z"></path>
                    </svg>
                </span>
            </th>
            <th onclick="sortTable(2)">
                Цена
                <span class="sort-icon">
                    <svg class="asc" viewBox="0 0 24 24" width="12" height="12">
                        <path d="M7 14l5-5 5 5z"></path>
                    </svg>
                    <svg class="desc" viewBox="0 0 24 24" width="12" height="12">
                        <path d="M7 10l5 5 5-5z"></path>
                    </svg>
                </span>
            </th>
            <th onclick="sortTable(3)">
                Цена
                <span class="sort-icon">
                    <svg class="asc" viewBox="0 0 24 24" width="12" height="12">
                        <path d="M7 14l5-5 5 5z"></path>
                    </svg>
                    <svg class="desc" viewBox="0 0 24 24" width="12" height="12">
                        <path d="M7 10l5 5 5-5z"></path>
                    </svg>
                </span>
            </th>
        </tr>
    </thead>
    <tbody>
         @foreach (var stock in Model)
        {
            <tr style="@(stock.Marketdata?.TRADINGSTATUS == "N" ? "background-color: grey" : "background-color: white;")" onclick="window.location.href='@Url.Action("DetailStock", "Stock", new { secId = stock.Security.SECID })'; return false">
                <td>
                    <div class="company-info">
                        @if (!(stock.Security.IconCompany is null))
                        {
                            <img src="@String.Format("data:image/gif;base64,{0}", Convert.ToBase64String(@stock.Security.IconCompany))" class="company-logo">
                        }
                        else
                        {
                            <img src="~/images/logo.jpg" class="company-logo"/>
                        }
                        <div>
                            <div class="company-name">@stock.Security.SHORTNAME</div>
                            <p class="company-description">@stock.Security.SECID</p>
                        </div>
                    </div>
                </td>
                <td>@stock.Security.SECID</td>
                <cost-difference item="@stock"></cost-difference>
                <td>
                    @{
                        string priceText = "-";
                        if (stock.Marketdata?.MARKETPRICE2 != null)
                        {
                            priceText = stock.Marketdata.MARKETPRICE2.Value.ToString();
                        }
                        else if (stock.Marketdata?.LAST != null)
                        {
                            priceText = stock.Marketdata.LAST.Value.ToString();
                        }
                        else if (stock.Security?.PREVPRICE != null)
                        {
                            priceText = stock.Security.PREVPRICE.Value.ToString();
                        }
                        @priceText
                    }
                </td>
                
            </tr>
        } 
    </tbody>
</table>
<style>
    .company-info {
        display: flex;
        align-items: center;
        gap: 10px;
    }

    .company-info {
        display: flex;
        align-items: center;
        gap: 10px;
    }
    .company-logo {
        width: 40px;
        height: 40px;
        object-fit: contain;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
    }
    th, td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f4f4f4;
        cursor: pointer;
        position: relative;
    }

        th:hover {
            background-color: #ddd;
        }

    tr:hover {
        background-color: #f5f5f5;
    }

    .sort-icon {
        display: inline-flex;
        flex-direction: column;
        margin-left: 8px;
        vertical-align: middle;
    }

        .sort-icon svg {
            fill: #888;
            transition: fill 0.2s;
            width: 12px;
            height: 12px;
        }

        .sort-icon .asc,
        .sort-icon .desc {
            display: none;
        }

    th.asc .sort-icon .asc,
    th.desc .sort-icon .desc {
        display: inline-block;
    }

    th.asc .sort-icon .asc {
        fill: #000;
    }

    th.desc .sort-icon .desc {
        fill: #000;
    }
</style>
<script>
    function sortTable(n) {
        var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
        table = document.getElementById("sortTable");
        switching = true;
        dir = "asc";

        // Удаляем классы сортировки у всех заголовков
        Array.from(table.getElementsByTagName("th")).forEach(th => {
            th.classList.remove("asc", "desc");
        });

        // Устанавливаем направление сортировки для текущего столбца
        if (table.getElementsByTagName("th")[n].classList.contains("asc")) {
            dir = "desc";
        } else {
            dir = "asc";
        }

        // Добавляем класс сортировки к текущему заголовку
        table.getElementsByTagName("th")[n].classList.add(dir);

        while (switching) {
            switching = false;
            rows = table.getElementsByTagName("TR");

            for (i = 1; i < (rows.length - 1); i++) {
                shouldSwitch = false;
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];

                if (dir == "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                } else if (dir == "desc") {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                        shouldSwitch = true;
                        break;
                    }
                }
            }

            if (shouldSwitch) {
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                switchcount++;
            } else {
                if (switchcount == 0 && dir == "asc") {
                    dir = "desc";
                    switching = true;
                }
            }
        }
    }
</script>